FROM python:3.13-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
  && rm -rf /var/lib/apt/lists/*

COPY pyproject.toml /app/pyproject.toml
COPY app/__init__.py /app/app/__init__.py
COPY app/common /app/app/common
COPY alembic.ini /app/alembic.ini
COPY migrations /app/migrations

RUN pip install --no-cache-dir .

ENV PYTHONUNBUFFERED=1

CMD ["alembic", "upgrade", "head"]

