#!/bin/bash
set -e

API_PASS=$(cat /run/secrets/db_password_api)
WRITER_PASS=$(cat /run/secrets/db_password_writer)
IMPORTER_PASS=$(cat /run/secrets/db_password_importer)

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE ROLE api_reader WITH LOGIN PASSWORD '$API_PASS';
    CREATE ROLE writer WITH LOGIN PASSWORD '$WRITER_PASS';
    CREATE ROLE importer WITH LOGIN PASSWORD '$IMPORTER_PASS';

    GRANT CONNECT ON DATABASE $POSTGRES_DB TO api_reader;
    GRANT USAGE ON SCHEMA public TO api_reader;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO api_reader;

    GRANT CONNECT ON DATABASE $POSTGRES_DB TO writer;
    GRANT USAGE ON SCHEMA public TO writer;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO writer;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT INSERT ON TABLES TO writer;

    GRANT CONNECT ON DATABASE $POSTGRES_DB TO importer;
    GRANT USAGE ON SCHEMA public TO importer;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO importer;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO importer;
EOSQL
